### ISSUE TITLE
Plugin: getSettings() instead of static settings variable

### ISSUE THREAD

**Issue by olleharstedt** [SamMousa/ls3-question-objects-spec#11]
Settings are set using a static variable. This way, it's not possible to dynamicall/programmatically decide what settings should be shown, e.g. if you want to show different settings considering database version or other plugin, etc. Any thoughts?

**Comment by SamMousa** [comment]
They are not static, they use getsettings they are just static in the
baseplugin implementation.

You can override it

**Comment by olleharstedt** [comment]
OK, good to know! Add it to the doc. ><

**Comment by LouisGac** [comment]
would be nice to rewrite the whole plugin system respecting the Yii way of doing (which also very close from the Ruby way of doing, or the Symphony way of doing... just the normal way of doing).

For example, here one of the most used and downloaded Yii 1 module : 
http://www.yiiframework.com/extension/yii-user/

Model, Views, controller, translations... 
And migration to handle the database version.

That's clean. That's beautiful.

**Comment by olleharstedt** [comment]
Feature already exists.
