### ISSUE TITLE
Stop using plugin system in favor of Yii modules

### ISSUE THREAD

**Issue by LouisGac** [SamMousa/ls3-question-objects-spec#13]
We're using Yii framework, a beautiful framework, used by dozen of thousands of coders over the world, written by extremely good coders, who spend their whole working time about framework questions since years. We're focusing on a survey system, they're focusing on questions such as : "_how to handle an extension system_".

So, they written an extension system, a very good one, handling any kind of problems an extension system can face, tested by a large community of application makers. It provides a way to build clean extensions, respecting standards such as MVC, thighly bound with Yii.

Instead of using this system, we're trying to use an "home made plugin system", full of problems, not respecting the most basic standards, not using the framework. So instead of focusing on our work problems like "how should we do mass actions", we quickly come to work on questions such as "how could we improve/correct/fix our home made plugin system".

That's a mistake. If we rather use the Yii Module system, any Yii coder on the world could write LimeSurvey modules. They could refer to the Yii documentation, instead of trying to understand the logic of our "_home made solution_".

**Comment by olleharstedt** [comment]
The question is what features Yii modules lack that we need, e.g. module management interface.

**Comment by SamMousa** [comment]
@LouisGac, as always you take an extreme standpoint that will proof impossible to defend. 
Also it seems you have no idea of the current state or the goal of the LS plugin system.
I'll try to explain this below, feel free to respond to any of these points if they are unclear.

1. The LS3 plugin system does support Yii modules.
2. Yii modules are not an alternative to plugins or a full solution for anything, i'll explain this in more detail below.

Yii modules offer a way to get a basic MVC app inside another MVC app. It doesn't do any of the things below:
- Define a standardized way to register your module without changing the config file.
- Define any LS specific API that developers can use to interact with our application domain.
- Define a way to alter system behavior.

Things you cannot do with a Yii module unless your application supports them:
1. Change the menu so your module is reachable with links.
2. Change the business logic so your module can actually provide a "service" to the application it is used in.

The LS plugin system basically adds these things while at the same time removing the requirement that you create a full Yii module.

You are allowed to create a Yii module and the only extra requirement LS3 has is that you add a configuration file telling the host system how and what to load. This does not negate the benefit of creating simple plugins that are not Yii modules.

Suggesting that Yii Modules can replace a plugin system is like suggesting we can remove plugins in its entirety thereby allowing all PHP developers to easily extend LimeSurvey. While theoretically that's already the case, it has all sorts of practical downsides.

Yii Modules are meant to be reusable modules for application developers, for example a Yii app could use a Yii Module for user management. This is not the same as dynamically having the application upload a module for user management.

I'll leave this open for now but if all you do is state "absolute truths" then it will never be a fruitful discussion.

**Comment by LouisGac** [comment]
We're suppose to build a survey system. 
You're building a framework.  

To quote you, that should be our only work:
-Define any LS specific API that developers can use to interact with our application domain.
-Define a way to alter system behavior.

**Comment by SamMousa** [comment]
We are doing exactly those things, the only difference is I don't have the illusion that adding random requirements like "must be a Yii Module" solves any problems.

**Comment by LouisGac** [comment]
Using the framework resolves most of the framework related questions.
Trying to build your own framework just keep you out of the application development. 

Eg:
We could have pretend to build our own specific CSS framework for LimeSurvey. Would have take a long time, and we would have faced so many problems to resolve.
We rather use Bootstrap framework: it solves most of the problem we would have faced without it. 

It's just the very same with the PHP framework.

**Comment by SamMousa** [comment]
Okay another non-argument. I'm done.

**Comment by LouisGac** [comment]
oh sorry I forgot : You wanted to build your own CSS framework too, and you was against the use of bootstrap...

**Comment by SamMousa** [comment]
That's not even close to being factually correct.
